name: Collect todos
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ID=$((10#$(TZ=Asia/Seoul date +%M) + 1))
          curl -s "https://jsonplaceholder.typicode.com/todos/$ID" -o /tmp/test.json
      - uses: actions/upload-artifact@v4
        with:
          name: test.json
          path: /tmp/test.json