name: Collect todos
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          minute=$(date +%M)
          ID=$((10#$minute + 1))
          mkdir -p data
          curl -s "https://jsonplaceholder.typicode.com/todos/$ID" -o data/test.json
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/test.json
          git commit -m "Update test.json (ID=$ID) [skip ci]" || echo "no changes"
          git push